// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlaBGWvENBeBUht7wBv5aUxJwLhK7finU',
    appId: '1:598120637300:web:094bc4ff8e8af1b7314221',
    messagingSenderId: '598120637300',
    projectId: 'inprep-ai-c0450',
    authDomain: 'inprep-ai-c0450.firebaseapp.com',
    storageBucket: 'inprep-ai-c0450.firebasestorage.app',
    measurementId: 'G-HHRS82VTYM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDriVe7NJ9PZ3xeiBP2-JDZCUNlPBe92TE',
    appId: '1:598120637300:android:c5bc37cc06b2cff0314221',
    messagingSenderId: '598120637300',
    projectId: 'inprep-ai-c0450',
    storageBucket: 'inprep-ai-c0450.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtNOGzPMs6I4wKG5hY3e1fUqAR1mC17Hc',
    appId: '1:598120637300:ios:5ec8644aa10f9165314221',
    messagingSenderId: '598120637300',
    projectId: 'inprep-ai-c0450',
    storageBucket: 'inprep-ai-c0450.firebasestorage.app',
    iosBundleId: 'com.example.inprepAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtNOGzPMs6I4wKG5hY3e1fUqAR1mC17Hc',
    appId: '1:598120637300:ios:5ec8644aa10f9165314221',
    messagingSenderId: '598120637300',
    projectId: 'inprep-ai-c0450',
    storageBucket: 'inprep-ai-c0450.firebasestorage.app',
    iosBundleId: 'com.example.inprepAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlaBGWvENBeBUht7wBv5aUxJwLhK7finU',
    appId: '1:598120637300:web:48b9fb46cc7af602314221',
    messagingSenderId: '598120637300',
    projectId: 'inprep-ai-c0450',
    authDomain: 'inprep-ai-c0450.firebaseapp.com',
    storageBucket: 'inprep-ai-c0450.firebasestorage.app',
    measurementId: 'G-7QT7H19FYY',
  );
}
